### ISSUE TITLE
Scikit-learn unpickle estimator RandomForestClassifier

### ISSUE THREAD

**Issue by ElpadoCan** [julianpietsch/baby#3]
Hi Julian, when I run BABY I get the following warning
```shell
C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.22.2.post1 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
```

I know it's because I have scikit-learn 1.2.2 but did you try to see if the warning can be ignored? Thanks!

**Comment by julianpietsch** [comment]
Hi Francesco, I've updated the code to ignore this warning (for running only). This should be included in the latest release on PyPI (0.30.5) and in 29abf75a86a4f
